name: ClientUnitTests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    env:
      working-directory: ./client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache
        uses: actions/cache@v1
        id: cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn
        working-directory: ${{env.working-directory}}
      - name: Builder
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn test
        working-directory: ${{env.working-directory}}
